<?php

namespace AppBundle\Repository;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends \Doctrine\ORM\EntityRepository
{
public function findAllCurrentPosts() {
    $now = new \DateTime('now');
    $qb = $this->createQueryBuilder('p')
        ->andWhere('p.published < :now')
        ->setParameter('now', $now)
        ->orderBy('p.published', 'DESC')
        ->getQuery();
    return $qb->execute();
}
}
